language: node_js
node_js:
- '6'

deploy:
    - provider: script
      script: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc 2>/dev/null
      on:
        branch: master

    - provider: script
      script: npm publish --access public
      on:
        branch: master
