language: node_js
node_js:
- '6'

deploy:
    - provider: script
      script: echo test npm token $NPM_TOKEN
      on:
        branch: master

    - provider: script
      script: npm publish --access public
      on:
        branch: master
