language: node_js
node_js:
- '6'

deploy:
    provider: script
    on:
        branch: master
    script: 
        - echo test first script
        - echo test second script
        - npm run ci-publish
